### ISSUE TITLE
Farmers Market Duping

### ISSUE THREAD

**Issue by Shota22** [sync0s/DustyRoads#44]
Wally and I tested buying last item in market. We both saw 1 Gold Ore, we were both able to buy the 1 Gold ore, duped Item.

**Comment by MrBohannon** [comment]
Pretty much if both users have the Flee market open at the same time and one user buys set item it wont update the UI and the other user can buy the item

**Comment by MrBohannon** [comment]
19:43:20 File \DustyRoads_Framework\addons\Housing\fn_sync_doors.sqf [dr_fnc_sync_doors], line 7
19:43:32 "[[""head_potato"",49],[""head_carrot"",31],[""head_wheat"",26],[""head_lettuce"",38],[""jar_clean"",20],[""jar_dirty"",40],[""copper_ore"",32],[""iron_ore"",20],[""silver_ore"",10],[""seed_potato"",13],[""quartz_ore"",1]]"
19:43:35 "Player transactions: [civ_4,""subtract"",false,60,3677,""Farmers Market Purchase""]"
19:43:35 "[[""head_potato"",49],[""head_carrot"",31],[""head_wheat"",26],[""head_lettuce"",38],[""jar_clean"",20],[""jar_dirty"",40],[""copper_ore"",32],[""iron_ore"",20],[""silver_ore"",10],[""seed_potato"",13],[""quartz_ore"",0]]"
19:43:36 "Player transactions: [civ_4,""subtract"",false,60,3617,""Farmers Market Purchase""]"
19:43:37 "[[""head_potato"",49],[""head_carrot"",31],[""head_wheat"",26],[""head_lettuce"",38],[""jar_clean"",20],[""jar_dirty"",40],[""copper_ore"",32],[""iron_ore"",20],[""silver_ore"",10],[""seed_potato"",13],[""quartz_ore"",1]]"
19:43:38 "Player transactions: [civ_4,""subtract"",false,60,3557,""Farmers Market Purchase""]"
19:43:38 "[[""head_potato"",49],[""head_carrot"",31],[""head_wheat"",26],[""head_lettuce"",38],[""jar_clean"",20],[""jar_dirty"",40],[""copper_ore"",32],[""iron_ore"",20],[""silver_ore"",10],[""seed_potato"",13],[""quartz_ore"",0]]"
19:43:39 "Player transactions: [civ_4,""subtract"",false,60,3497,""Farmers Market Purchase""]"
19:43:39 "[[""head_potato"",49],[""head_carrot"",31],[""head_wheat"",26],[""head_lettuce"",38],[""jar_clean"",20],[""jar_dirty"",40],[""copper_ore"",32],[""iron_ore"",20],[""silver_ore"",10],[""seed_potato"",13],[""quartz_ore"",1]]"
19:43:41 "Player transactions: [civ_4,""subtract"",false,60,3437,""Farmers Market Purchase""]"
19:43:41 "[[""head_potato"",49],[""head_carrot"",31],[""head_wheat"",26],[""head_lettuce"",38],[""jar_clean"",20],[""jar_dirty"",40],[""copper_ore"",32],[""iron_ore"",20],[""silver_ore"",10],[""seed_potato"",13]]"
