### ISSUE TITLE
Lost all my silver in bank

### ISSUE THREAD

**Issue by Zacharylo1** [sync0s/DustyRoads#83]
Logged on today and spawned bottom left of map and respawned lost my gear like normal but went to get silver to buy more and i have 0 so am unable to even buy seeds to earn money.

No clue as too cause sorry

**Comment by sync0s** [comment]
Hey Zachary,

We have had some issues with characters stuff getting wiped, which is what it sounds like happened to you. Were you able to talk to someone to get your account fixed up? If not, drop in discord or teamspeak and message a director or support staff.

Thank for reporting this

**Comment by Zacharylo1** [comment]
got it taken care of
